### ISSUE TITLE
rwhnf clash upcoming with next deepseq

### ISSUE THREAD

**Issue by phadej** [haskell/parallel#13]
Ambiguous occurrence ‘rwhnf’
    It could refer to either ‘Control.DeepSeq.rwhnf’,
                             imported from ‘Control.DeepSeq’ at Control/Parallel/Strategies.hs:147:1-22
                          or ‘Control.Parallel.Strategies.rwhnf’,
                             defined at Control/Parallel/Strategies.hs:741:1

**Comment by phadej** [comment]
I see this is fixed in `master`, but not in any released version.

**Comment by hvr** [comment]
to be fair, I'd wait till we know for sure whether the next `deepseq` rls will be a major or a minor ver... :-)

but as soon as that's done I'll look to it myself asap that this is adressed

**Comment by phadej** [comment]
Well, this can be solved with explicit import list too, if that's an option?

**Comment by hvr** [comment]
@phadej yeah, I'd like that more than the current CPP use (or alternatively use qualified imports)

**Comment by RyanGlScott** [comment]
Well, GHC 8.2.1-rc1 is here. What is the current status of this, @hvr?

**Comment by hvr** [comment]
@RyanGlScott For the record, GHC 8.2.1-rc1 hasn't been git tagged yet... i.e. it's not offical yet ;-)

That being said... see http://hackage.haskell.org/package/parallel-3.2.1.1 :-)
