### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by hyiltiz** [haskell/parallel#14]
Neither Hackage nor Github points to any documentation. Are users expected to read through the implementation in the source code?

**Comment by hvr** [comment]
Are you saying that the documentation at http://hackage.haskell.org/package/parallel-3.2.1.1/docs/Control-Parallel-Strategies.html is not sufficient? If so, what's missing; what can we improve?

The concepts behind this package originate from e.g. http://community.haskell.org/~simonmar/papers/strategies.pdf 

If you want a more thorough coverage of parallel programming in Haskell, I'd recommend reading @simonmar's [*Parallel and Concurrent Programming in Haskell* book](http://chimera.labs.oreilly.com/books/1230000000929/index.html)

**Comment by hyiltiz** [comment]
Thanks for pointing to the paper. I'll check it out.

**Comment by Profpatsch** [comment]
Adding the paper to the documentation would help, I guess.
