### ISSUE TITLE
Regression: The behaviour of `rparWith r0` has changed

### ISSUE THREAD

**Issue by Borgvall** [haskell/parallel#35]
For years the documented (and actual) behaviour of `rparWith r0`, was to create a spark that does no evaluation. However since commit 9ea4c073e9fafc81d2a771831a2f913153c36214 the spark will evaluate to weak head normal form.

I have restored the documented behaviour in pull request #34.

**Comment by treeowl** [comment]
No, it never had that behavior.

**Comment by Borgvall** [comment]
It did. Just run the test program with ghc 8.0.2 and parallel 3.2.1.0.

**Comment by treeowl** [comment]
I see. I was confused by the documentation suggesting ``rparWith s = rpar `dot` s``. The documentation definitely needs to be clarified. Tonight I'll come up with a fix that doesn't use `realWorld#`.
