### ISSUE TITLE
Hackage release needs a revision to bump base upper bound for GHC 8.8.1

### ISSUE THREAD

**Issue by merijn** [haskell/parallel#54]
The release on Hackage has a <4.13 bound on base, this should be updated to be <4.14 so it compiles with GHC 8.8

**Comment by glguy** [comment]
Fix in revision 1: http://hackage.haskell.org/package/parallel-3.2.2.0/revisions

**Comment by hvr** [comment]
closing since this was already anticipated in Git via 4a04f41b7e2857ab8a09bcb8ed0b346516b0c817 (before GHC 8.8.1 was released)
