### ISSUE TITLE
Build failures: "No instance for (Ix i)"

### ISSUE THREAD

**Issue by sajith** [haskell/parallel#6]
See travis-ci.org logs, such as this:

https://travis-ci.org/haskell/parallel/builds/46062982

Looks like the build failures are caused by these two commits:

https://github.com/haskell/parallel/commit/e4e4228ba94178cf31b97fe81b94bff3de6fce03
https://github.com/haskell/parallel/commit/dfb8fe517b10588847ca285f93300fa7f1552857

This is certainly not code I understand, but - maybe those commits should be reversed?

**Comment by rwbarton** [comment]
The constraints are unnecessary in 7.11 due to https://github.com/ghc/ghc/commit/c409b6f30373535b6eed92e55d4695688d32be9e#diff-e0fd0846704abfed64ee2ea963daeb06L557. I suppose the parallel package is supposed to be upgradeable, so in principle I guess we should provide the appropriate type signature with CPP... ugh.

**Comment by hvr** [comment]
> I suppose the parallel package is supposed to be upgradeable,

btw, the `parallel` package is an ordinary package (i.e. not part of the GHC bindists)

**Comment by rwbarton** [comment]
Oh, so it is. (What is it doing in the GHC tree then? Perhaps wandering a bit off topic...)

**Comment by hvr** [comment]
@rwbarton iirc it's for the testsuite

**Comment by sajith** [comment]
@hvr Now that I have your attention, can you also take a look at PR #5?   It is minor -- it just updates a couple of links in the documentation.

Thanks, and apologies about bringing this up at the wrong place. :-)

**Comment by konsumlamm** [comment]
This has been fixed in https://github.com/haskell/parallel/commit/0ec7fe287db9b837af5baab2e9566ac9bef19625.
